# Generated by Django 4.2 on 2023-05-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='jobs',
        ),
    ]
