# Generated by Django 4.2 on 2023-05-10 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_multipleimage_delete_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.skilled_companies')),
            ],
        ),
        migrations.DeleteModel(
            name='MultipleImage',
        ),
    ]
