# Generated by Django 4.2 on 2023-05-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_multipleimages_delete_multipleimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipleimages',
            name='posts',
        ),
    ]
