# Generated by Django 4.2 on 2023-05-10 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_multipleindimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleindimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.skilled_individuals'),
        ),
    ]
